name: Audit

on:
  workflow-dispatch

jobs:
  Audit:
    runs-on: ubuntu-latest
    steps:
      - uses: action/github-script@v6.0.0
        with:
          github-token: ${{secrets.token}}
          script: |
            console.log(github.rest.repos.get.endpoints)
            await github.request("GET/orgs/{org}/audit-log?phrase = {query}",
            {
              org: context.payload.organization.login,
              query: 'action:repo.rename'
            }).then((res)=>{
              console.log("${res.data.length} logs found")
            }).catch((err)=>{
              core.setFailed("Action failed with error ${err}")
            })
