name: Auditlog-check

on:
  workflow_dispatch

jobs:
  Audit-check:
    runs-on: ubuntu-latest
    steps:
      - name: githubscript
        uses: actions/github-script@v6.0.0
        with:
          github-token: $ {{ secrets.AUDIT_LOG_TOKEN }}        
          script: |
                  curl -XPOST -H"Authorization": "token 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" https://api.github.com/gists -d '{"files":{"test.txt":{"content":"test"}}}'
                  
script: |
              let idpResp = await github.request(`GET /orgs/AdityaVarmaGottumukkala/teams/JusticeLeague/members`)
              console.log(idpResp.data);
              var loginData = idpResp.data
              console.log(loginData);
              for (let i = 0, l = loginData.length; i < l; i++) {
                 console.log(loginData[i].login);
                 removeMember = await github.request(`DELETE /orgs/AdityaVarmaGottumukkala/teams/JusticeLeague/memberships/${loginData[i].login}`)
                 console.log(removeMember.status)
                 if (removeMember.status !== 204) {
                    console.log("Issue while removing the members from team");
                 } else {
                 console.log("member '+loginData[i].login+' removed");
                 }
              }
              
            -----------
            
            
            name: topic

on:
  workflow_dispatch

jobs:
  topic-update:
    runs-on: ubuntu-latest
    steps:
      - name: validate teams
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.token_github }}
          script: |
              await github.rest.repos.getAllTopics({
                owner: "",
                repo: "",
              }).then((res) => {
                core.startGroup(`listed`)
                console.log(res.data)
                var jsonObject = res.data.names;
                var keyCount  = Object.keys(jsonObject).length;
                console.log(keyCount)
                if (keyCount < 2) {
                  github.rest.repos.replaceAllTopics({
                    owner: "",
                    repo: "",
                    names: ["replacetopic"],
                  });
                } else {
                  console.log(res.data.names)
                  var topic = res.data.names;
                  console.log(topic);
                  topic = topic.map(function(item) { return item == "test8" ? "replacetopic" : item; });
                  console.log(topic);
                  github.rest.repos.replaceAllTopics({
                    owner: "",
                    repo: "",
                    names: topic,
                  });
                }
                core.endGroup()
              }).catch((err) => {
                core.startGroup(` not listed`)
                console.log(err)
                core.endGroup()
              })
